/**
 * 
 */
package application;

import javafx.stage.Stage;

/**
 * A stage used to show search results after click the search button
 * 
 * @author Ruizhe Wang
 * 
 * NOTE: DO NOT edit this file unless you want to finish this part.
 *
 */
public class SearchStage extends Stage {

}
